# Copyright (c) 2021 Veli Matti Lastumäki (Velsku at lampopumput.info),
#                    Joonas Ihonen (puu at lampopumput.info),
#                    Ilkka Roivainen (iro at lampopumput.info)
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

logger:

substitutions:
  platform_type:                      'esp8266'
  board_type:                         'd1_mini'
#  dallas_address_heat_exchanger_temp: '0x653C01D607697928'
#  dallas_address_outdoor_temp:        '0x93000802B67D1E10'
  
#  dallas_address_heat_exchanger_temp: '0x253C01D075425928'
#  dallas_address_outdoor_temp:        '0x8F3C01D07558F828'
#  dallas_address_test:                '0xCC02189245841C28'
#  dallas_address_test2:               '0xE33C01D0753C9028'

  dallas_address_outdoor_temp:        '0x253C01D075425928'
  dallas_address_heat_exchanger_temp: '0xE33C01D0753C9028'
  dallas_address_test:                '0x8F3C01D07558F828'
  dallas_address_test2:               '0xCC02189245841C28'

# 1 '0x8F3C01D07558F828' Alaputki (pysty)
# 2 '0xCC02189245841C28' Ylaputki (klipsilla)
# 3 '0xE33C01D0753C9028' Alkup. putki (vino)


# MQTT topics. These are inside single quotes:
  topic_heatexchanger:                'ln25/sensor/temperature/out/heatexc'
  topic_outdoor:                      'ln25/sensor/temperature/out/inlet_avg'
  topic_test:                         'ln25/sensor/temperature/out/heatexc_low'
  topic_test2:                        'ln25/sensor/temperature/out/heatexc_high'
  topic_delta:                        'ln25/sensor/temperature/out/delta'
  topic_current:                      'ln25/sensor/current'
  topic_rssi:                         'ln25/sensor/wifi/rssi'
  topic_outdoor_errors:               'ln25/sensor/error/out_inlet_errors'
  topic_exchanger_errors:             'ln25/sensor/error/out_heatexc_errors'
  topic_uptime:                       'ln25/sensor/uptime'
#  topic_dht_temp:                     'ln25/sensor/temperature/out/temp'
#  topic_dht_temp:                     'ln25/sensor/temperature/out/temp'
#  topic_dht_humi:                     'ln25/sensor/temperature/out/humidity'

# MQTT topics. Notice that these are inside both single and double quotes:
  topic_outdoor_raw:                  '"ln25/sensor/temperature/out/inlet"'
  topic_state:                        '"ln25/sensor/state/fsm_state"'
  topic_excess_timer_state:           '"ln25/sensor/state/excess_timer"'
  topic_min_heating_timer_state:      '"ln25/sensor/state/min_heating_timer"'
  topic_defrosting_timer_state:       '"ln25/sensor/state/topic_defrosting_timer"'
  topic_start_defrosting_timer_state: '"ln25/sensor/state/topic_start_defrosting_timer"'
  topic_force_defrost_timer_state:    '"ln25/sensor/state/force_defrost_timer"'
  topic_reset_timer_state:            '"ln25/sensor/state/reset_timer"'
  topic_error:                        '"ln25/sensor/state/error"'
  topic_current_filtered:             '"ln25/sensor/current_filtered"'
  topic_delta_threshold:              '"ln25/sensor/delta_threshold"'


  dallas_pin:                         'D7'
  relay_pin:                          'D1'

